server:
  port: 8080
spring:
  application:
    name: team5-project
  datasource:
    url: jdbc:postgresql://localhost:5432/team5
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create
api:
  secret: noop
  expiration-time: 150000
  token-prefix: Bearer
  signup-url: /users


