
create table academicblock
(
    id integer not null
        constraint academicblock_pkey
            primary key,
    begindate date not null,
    enddate date not null,
    name varchar(255) not null,
    semester varchar(255) not null
);

alter table academicblock owner to zendo;

create table academicblockreaddto
(
    id integer not null
        constraint academicblockreaddto_pkey
            primary key,
    begindate date not null,
    enddate date not null,
    name varchar(255) not null,
    semester varchar(255) not null
);

alter table academicblockreaddto owner to zendo;

create table course
(
    id integer not null
        constraint course_pkey
            primary key,
    abbreviation varchar(5),
    name varchar(255)
);

alter table course owner to zendo;

create table coursedescription
(
    description varchar(4000),
    id integer not null
        constraint coursedescription_pkey
            primary key
        constraint fkhgrhbrfyk1mhtkps2elu5hslr
            references course
);

alter table coursedescription owner to zendo;

create table coursereaddto
(
    id integer not null
        constraint coursereaddto_pkey
            primary key,
    abbreviation varchar(5),
    name varchar(255)
);

alter table coursereaddto owner to zendo;

create table location
(
    id integer generated by default as identity
        constraint location_pkey
            primary key,
    description varchar(255),
    locationname varchar(255)
);

alter table location owner to zendo;

create table person
(
    id integer generated by default as identity
        constraint person_pkey
            primary key,
    emailaddress varchar(255) not null,
    firstname varchar(255) not null,
    lastname varchar(255) not null
);

alter table person owner to zendo;

create table faculty
(
    title varchar(255),
    id integer not null
        constraint faculty_pkey
            primary key
        constraint fkmjipb8roamp147iwf5onc3fof
            references person
);

alter table faculty owner to zendo;

create table courseoffering
(
    id integer generated by default as identity
        constraint courseoffering_pkey
            primary key,
    capacity integer not null,
    period varchar(255),
    startdate date,
    blockid integer
        constraint fklc3oag8u4jg3fl6uohk23c0s6
            references academicblock,
    courseid integer
        constraint fk6nautvk22m3x6kndotbuf0rnr
            references course,
    facultyid integer
        constraint fk9imblephkln0vb028t82m79nh
            references faculty
);

alter table courseoffering owner to zendo;

create table person_roles
(
    person_id integer not null
        constraint fkg0p2bchukkd0meo9lg9x4r3h9
            references person,
    roles varchar(255)
);

alter table person_roles owner to zendo;

create table student
(
    barcode varchar(13) not null
        constraint uk_6xmhr0731ty108b4ouhfdisyh
            unique,
    entrydate date,
    status varchar(255),
    studentid varchar(11) not null,
    track varchar(255),
    visastatus varchar(255),
    id integer not null
        constraint student_pkey
            primary key
        constraint fk3bkmp4kohbl54m14tb2fcqya3
            references person
);

alter table student owner to zendo;

create table registration
(
    id integer generated by default as identity
        constraint registration_pkey
            primary key,
    date date,
    offering_id integer
        constraint fks9nefgh6tqtqkdyxffah7g19f
            references courseoffering,
    student_id integer
        constraint fkeb2bnppytukjyrylpvnfxto1r
            references student
);

alter table registration owner to zendo;

create table timeslot
(
    id integer generated by default as identity
        constraint timeslot_pkey
            primary key,
    endtime time,
    starttime time,
    timeslotid varchar(255)
        constraint uk_grxebwnu2nhefxsbdb2pr4a2w
            unique,
    title varchar(255)
);

alter table timeslot owner to zendo;

create table classsession
(
    id integer generated by default as identity
        constraint classsession_pkey
            primary key,
    date date,
    courseoffering_id integer
        constraint fkqg2xjbk9w6484850sek13dcii
            references courseoffering,
    location_id integer
        constraint fkoi7goddnvw6hucq3n2jmjnuvu
            references location,
    timeslot_id integer
        constraint fk8wfxx9itvenk6ch75equp443c
            references timeslot
);

alter table classsession owner to zendo;

create table barcoderecord
(
    id integer generated by default as identity
        constraint barcoderecord_pkey
            primary key,
    attendance timestamp,
    classsession_id integer
        constraint fkfsh7oqpb2b5raicj12uwelci0
            references classsession,
    studentid integer
        constraint fkl9ojhraicaufkowkan1anjsdi
            references student
);

alter table barcoderecord owner to zendo;

