create table role
(
    id   integer generated by default as identity
        constraint role_pkey
            primary key,
    type varchar(10)
        constraint uk_4q3pkloi6sbruhftvl7vx7krr
            unique
);

alter table role
    owner to zendo;

